<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_theme().
 */
function levchik_theme($existing, $type, $theme, $path) {
  return [
    'levchik_guests' => [
      'variables' => [
        'guests' => NULL,
      ],
      'template' => 'guests',
    ],
    'levchik_guest_button' => [
      'variables' => [
        'id' => NULL,
      ],
      'template' => 'guest-buttons',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function levchik_preprocess_levchik_guest_button(&$variables) {
  $variables['#attached']['library'][] = 'levchik/buttons';
}
